-- ============================================================
-- 谢氏族譜 Seed Data — 163 members, 24 generations
-- Source: familytree2.csv
-- Run AFTER schema.sql
-- ============================================================

-- Clear existing data before seeding
TRUNCATE TABLE family_members RESTART IDENTITY CASCADE;

INSERT INTO family_members (id, line1, line2, line3, position, refs, is_deceased) VALUES
(1,   '始祖 大帽',                NULL,                      NULL,                  '一世',   ARRAY[2],                            TRUE),
(2,   '极贵庸(1297-1307)',        '吴氏',                    NULL,                  '二世',   ARRAY[3],                            TRUE),
(3,   '生馬成(1330-1379)',        '王氏',                    '杨氏(继)',             '三世',   ARRAY[4,5],                          TRUE),
(4,   '仪仙祖',                   '许氏',                    NULL,                  '四世',   ARRAY[6],                            TRUE),
(5,   '仪仙举',                   NULL,                      NULL,                  '四世',   NULL,                                TRUE),
(6,   '象郁(1394-1453)',          '卓氏(1397-1467)',         NULL,                  '五世',   ARRAY[7,8,9,10],                     TRUE),
(7,   '卦荣奇(1418-1484)',        '陈氏',                    '侧室黄',              '六世',   ARRAY[11,12,13,14,15,16],            TRUE),
(8,   '贲邱',                     NULL,                      NULL,                  '六世',   NULL,                                TRUE),
(9,   '居易',                     NULL,                      NULL,                  '六世',   NULL,                                TRUE),
(10,  '景阳',                     NULL,                      NULL,                  '六世',   NULL,                                TRUE),
(11,  '画环',                     NULL,                      NULL,                  '七世',   NULL,                                TRUE),
(12,  '画璁',                     NULL,                      NULL,                  '七世',   NULL,                                TRUE),
(13,  '画秉',                     NULL,                      NULL,                  '七世',   NULL,                                TRUE),
(14,  '画琚',                     NULL,                      NULL,                  '七世',   NULL,                                TRUE),
(15,  '画玄',                     NULL,                      NULL,                  '七世',   NULL,                                TRUE),
(16,  '画璋(1457-1497)',          '杨氏(1459-1546)',         NULL,                  '七世',   ARRAY[17,18],                        TRUE),
(17,  '辩称',                     NULL,                      NULL,                  '八世',   NULL,                                TRUE),
(18,  '辩侯',                     '孙氏',                    NULL,                  '八世',   ARRAY[19,20,21,22,23],               TRUE),
(19,  '乾沐',                     NULL,                      NULL,                  '九世',   NULL,                                TRUE),
(20,  '乾浓',                     '林氏',                    NULL,                  '九世',   ARRAY[24,25,26,27,28,29,30,31],      TRUE),
(21,  '乾游',                     NULL,                      NULL,                  '九世',   NULL,                                TRUE),
(22,  '乾涣',                     NULL,                      NULL,                  '九世',   NULL,                                TRUE),
(23,  '乾池',                     NULL,                      NULL,                  '九世',   NULL,                                TRUE),
(24,  '坤先正',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(25,  '坤先齐(1553-1627)',        '宋氏(15XX-1626)',         NULL,                  '十世',   ARRAY[32,33],                        TRUE),
(26,  '坤先知',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(27,  '坤先修',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(28,  '坤先遗',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(29,  '坤先选',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(30,  '坤先科',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(31,  '坤先第',                   NULL,                      NULL,                  '十世',   NULL,                                TRUE),
(32,  '卿会科',                   '黄氏',                    NULL,                  '十一世', ARRAY[34,35,36,37],                  TRUE),
(33,  '会礼',                     NULL,                      NULL,                  '十一世', NULL,                                TRUE),
(34,  '儒挺举',                   NULL,                      NULL,                  '十二世', NULL,                                TRUE),
(35,  '儒挺峰',                   NULL,                      NULL,                  '十二世', NULL,                                TRUE),
(36,  '儒挺风(1625-1678)',        '江氏(1627-1644)',         '(继1639-1721)',        '十二世', ARRAY[38,39,40],                     TRUE),
(37,  '儒仕叔',                   NULL,                      NULL,                  '十二世', NULL,                                TRUE),
(38,  '臣秀(1668-1743)',          '许氏(1682-1744)',         NULL,                  '十三世', ARRAY[41,42,43,44,45],               TRUE),
(39,  '臣未',                     NULL,                      NULL,                  '十三世', NULL,                                TRUE),
(40,  '臣万',                     NULL,                      NULL,                  '十三世', NULL,                                TRUE),
(41,  '檀送(1704-1773)',          '张氏(1706-1745)',         NULL,                  '十四世', ARRAY[46,47,48,49,50,51],            TRUE),
(42,  '檀祥',                     NULL,                      NULL,                  '十四世', NULL,                                TRUE),
(43,  '檀瑞',                     NULL,                      NULL,                  '十四世', NULL,                                TRUE),
(44,  '檀八',                     NULL,                      NULL,                  '十四世', NULL,                                TRUE),
(45,  '檀旺',                     NULL,                      NULL,                  '十四世', NULL,                                TRUE),
(46,  '懋寅',                     NULL,                      NULL,                  '十五世', NULL,                                TRUE),
(47,  '懋油',                     NULL,                      NULL,                  '十五世', NULL,                                TRUE),
(48,  '懋黄',                     NULL,                      NULL,                  '十五世', NULL,                                TRUE),
(49,  '懋欣',                     NULL,                      NULL,                  '十五世', NULL,                                TRUE),
(50,  '懋豆',                     NULL,                      NULL,                  '十五世', NULL,                                TRUE),
(51,  '懋六',                     '无氏',                    NULL,                  '十五世', ARRAY[52],                           TRUE),
(52,  '孝领(1773-1837)',          '翁氏(1773-1846)',         NULL,                  '十六世', ARRAY[53],                           TRUE),
(53,  '友冬梅(1808-1846)',        '魏氏(1821-1855)',         NULL,                  '十七世', ARRAY[54,55],                        TRUE),
(54,  '传着(1841-1913)',          '许氏(1847-1881)',         '陈氏(继1834-1912)',   '十八世', ARRAY[56,57],                        TRUE),
(55,  '传错',                     NULL,                      NULL,                  '十八世', NULL,                                TRUE),
(56,  '世沁(1878-1897)',          '王氏(1875-1919)',         NULL,                  '十九世', ARRAY[58,59,60],                     TRUE),
(57,  '世告(1874-1949)',          '王氏(1893-1940)',         NULL,                  '十九世', NULL,                                TRUE),
(58,  '江漢(1896-1945)',          '祥娘(1901-1972)',         NULL,                  '二十世', ARRAY[61,62,63,64,65],               TRUE),
(59,  '仁景(1902-1947)',          '许氏(1911-19XX)',         '许氏(继1921-2000)',   '二十世', NULL,                                TRUE),
(60,  '德金狗(1922-20XX)',        '黄氏(1930-20XX)',         NULL,                  '二十世', NULL,                                TRUE),
(61,  '谢文兴(19XX-XXXX)',        '林眼(19XX-XXXX)',         NULL,                  '二一世', ARRAY[66,67,68,69,70,71,72,73,74],   FALSE),
(62,  '谢水泉(1928-1995)',        '陈来城(1930-1992)',       NULL,                  '二一世', ARRAY[75,76,77,78,79,80,81,82],      TRUE),
(63,  '谢水旺',                   NULL,                      NULL,                  '二一世', NULL,                                FALSE),
(64,  '谢楜椒(19XX-XXXX)',        '陈水盛(19XX-XXXX)',       NULL,                  '二一世', ARRAY[83,84,85,86],                  FALSE),
(65,  '谢金吉',                   '陈连灯(19XX-XXXX)',       NULL,                  '二一世', ARRAY[87,88,89,90,91],               FALSE),
(66,  '谢章烟',                   '萧玉风',                  NULL,                  '二十二世',ARRAY[92,93,94,95],                 FALSE),
(67,  '谢申友',                   NULL,                      NULL,                  '二十二世',NULL,                               FALSE),
(68,  '谢再生',                   '林珠风',                  NULL,                  '二十二世',ARRAY[96,97],                       FALSE),
(69,  '谢进财',                   NULL,                      NULL,                  '二十二世',NULL,                               FALSE),
(70,  '谢永财',                   '陈钻珠',                  NULL,                  '二十二世',ARRAY[98,99,100,101],               FALSE),
(71,  '谢永在',                   '廖佩云',                  NULL,                  '二十二世',ARRAY[102,103],                     FALSE),
(72,  '谢永顺',                   '蔡岫娟',                  NULL,                  '二十二世',ARRAY[104,105],                     FALSE),
(73,  '谢永义',                   '卓宝莲',                  NULL,                  '二十二世',ARRAY[106,107],                     FALSE),
(74,  '谢丽妹',                   '陈文生',                  NULL,                  '二十二世',ARRAY[108,109],                     FALSE),
(75,  '谢永杉',                   '陈文嬿',                  NULL,                  '二十二世',ARRAY[110,111],                     FALSE),
(76,  '谢永德',                   '史竹叶',                  NULL,                  '二十二世',ARRAY[112,113],                     FALSE),
(77,  '谢永福',                   '李柳美',                  NULL,                  '二十二世',ARRAY[114,115,116],                 FALSE),
(78,  '谢永骞',                   '林赛春',                  NULL,                  '二十二世',ARRAY[117,118],                     FALSE),
(79,  '谢永成',                   '陈素云',                  NULL,                  '二十二世',ARRAY[119],                         FALSE),
(80,  '杨宝玉',                   '陈亚历(19XX-XXXX)',       NULL,                  '二十二世',ARRAY[120,121,122,123,124],          FALSE),
(81,  '谢钻珠',                   '陈吉源',                  NULL,                  '二十二世',ARRAY[125,126],                     FALSE),
(82,  '谢钻娘',                   'Leslie Joseph',           NULL,                  '二十二世',ARRAY[127,128],                     FALSE),
(83,  '陈玉英(19XX-XXXX)',        '刘再练(19XX-XXXX)',       NULL,                  '二十二世',NULL,                               FALSE),
(84,  '陈钦賜(19XX-XXXX)',        '辛金贵(19XX-XXXX)',       NULL,                  '二十二世',NULL,                               FALSE),
(85,  '陈月云',                   '辛金贵(19XX-XXXX)',       NULL,                  '二十二世',NULL,                               FALSE),
(86,  '陈欽忠',                   NULL,                      NULL,                  '二十二世',NULL,                               FALSE),
(87,  '陈全忠(19XX-XXXX)',        NULL,                      NULL,                  '二十二世',NULL,                               FALSE),
(88,  '陈质秀',                   '陈岳冠',                  NULL,                  '二十二世',NULL,                               FALSE),
(89,  '陈秀美',                   '陈志华',                  NULL,                  '二十二世',NULL,                               FALSE),
(90,  '陈美兰',                   '林平春',                  NULL,                  '二十二世',NULL,                               FALSE),
(91,  '陈全阳',                   NULL,                      NULL,                  '二十二世',NULL,                               FALSE),
(92,  '谢志荣',                   '李嘉欣',                  NULL,                  '二十三世',ARRAY[129,130,131],                 FALSE),
(93,  '谢志和',                   '黄秀玲',                  NULL,                  '二十三世',NULL,                               FALSE),
(94,  '谢志明',                   '李美莲',                  NULL,                  '二十三世',ARRAY[132,133],                     FALSE),
(95,  '谢雪铃',                   NULL,                      NULL,                  '二十三世',ARRAY[134,135],                     FALSE),
(96,  '谢志宝',                   '林妍贝',                  NULL,                  '二十三世',NULL,                               FALSE),
(97,  '谢志成',                   '连彗利',                  NULL,                  '二十三世',ARRAY[136],                         FALSE),
(98,  '谢志庆',                   '王妮绮',                  NULL,                  '二十三世',ARRAY[137,138],                     FALSE),
(99,  '谢志伟',                   '陈秀莉',                  NULL,                  '二十三世',ARRAY[139,140],                     FALSE),
(100, '谢秉良',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(101, '谢美君',                   '吴冠贤',                  NULL,                  '二十三世',NULL,                               FALSE),
(102, '谢志华',                   '张僡玹',                  NULL,                  '二十三世',NULL,                               FALSE),
(103, '谢雪芳',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(104, '谢恊频',                   'William Soliman',         NULL,                  '二十三世',NULL,                               FALSE),
(105, '谢智强',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(106, '谢志勇',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(107, '谢雪薇',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(108, '陈冠睿',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(109, '陈思蒨',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(110, '谢健鸿',                   '梁婉玉',                  NULL,                  '二十三世',ARRAY[141,142],                     FALSE),
(111, '谢佳芬',                   '梁俊龙',                  NULL,                  '二十三世',ARRAY[143,144],                     FALSE),
(112, '谢佳慧',                   '薛世豪',                  NULL,                  '二十三世',NULL,                               FALSE),
(113, '谢健聪',                   '黄露怡',                  NULL,                  '二十三世',ARRAY[145],                         FALSE),
(114, '谢健翔',                   '林惠雯',                  NULL,                  '二十三世',ARRAY[146,147],                     FALSE),
(115, '谢健欣',                   '佃秀仪',                  NULL,                  '二十三世',ARRAY[148,149,150],                 FALSE),
(116, '谢健龙',                   '陈焕苓',                  NULL,                  '二十三世',ARRAY[151,152],                     FALSE),
(117, '谢胜杰',                   '刘俐嫣',                  NULL,                  '二十三世',ARRAY[153],                         FALSE),
(118, '谢雄杰',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(119, '谢佳佳',                   '林思捷',                  NULL,                  '二十三世',NULL,                               FALSE),
(120, '陈淑芬',                   'Sapmaz Arif',             NULL,                  '二十三世',ARRAY[154,155],                     FALSE),
(121, '陈志雄',                   'Tina Tan',                NULL,                  '二十三世',ARRAY[156,157],                     FALSE),
(122, '陈淑玲',                   '吴坤光',                  NULL,                  '二十三世',ARRAY[158,159],                     FALSE),
(123, '陈淑云',                   '郑庆源',                  NULL,                  '二十三世',ARRAY[160],                         FALSE),
(124, '陈文彬',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(125, '陈乐琳',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(126, '陈丽铃',                   NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(127, '毅渊',                     NULL,                      NULL,                  '二十三世',NULL,                               FALSE),
(128, '轩文',                     '赖紫婷',                  NULL,                  '二十三世',ARRAY[161,162,163],                 FALSE),
(129, '谢光正',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(130, '谢光智',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(131, '谢咏琦',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(132, '谢定諹',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(133, '谢依芸',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(134, '俊杰Alex',                 NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(135, '丽婷Amelia',               NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(136, '谢铮慨',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(137, '谢鸿祥',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(138, '谢家怡',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(139, '谢光宇',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(140, '谢孜宇',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(141, '谢彤宁',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(142, '谢婕宁',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(143, '梁智瑞',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(144, '梁芷绮',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(145, '谢颖萱',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(146, '谢义泽',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(147, '谢义乐',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(148, '谢凯杰',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(149, '谢恺琪',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(150, '谢凯文',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(151, '谢义凯',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(152, '谢凯乐',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(153, '谢镐宇',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(154, '唐玮',                     NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(155, '唐琪',                     NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(156, '陈乐恩',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(157, '陈源泰',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(158, '吴婧宁',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(159, '吴倩宁',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(160, '郑惠心',                   NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(161, '凯莉',                     NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(162, '敏恩',                     NULL,                      NULL,                  '二十四世',NULL,                               FALSE),
(163, '余恩',                     NULL,                      NULL,                  '二十四世',NULL,                               FALSE);
